### ISSUE TITLE
when2 AttributeError: 'Dummy' has no attribute configured

### ISSUE THREAD

**Issue by Wouter1** [kaste/mockito-python#90]
when2 seems not to work as expected.

```
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
```
mockito 1,5,3 , also not working with 1.5.1

how to reproduce
```
from mockito import mock,when2
class A:
  def f(self):
    return "no"
a=mock(A)
when2(a.f).thenReturn("yes")
```

gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/PythonVenvs/geniusweb1targz/venv/lib/python3.8/site-packages/mockito/mocking.py", line 299, in __getattr__
    raise AttributeError(
AttributeError: 'Dummy' has no attribute 'f' configured
```

expected: a with mocked f function

Strange is that it works fine with some built-in functions:

```
when2(a.__repr__).thenReturn("yes")
<mockito.invocation.AnswerSelector object at 0x7fb3eceb5cd0>
```

Maybe related to #57

**Comment by kaste** [comment]
`mock(A)` provides a spec (`A`) which makes the mock `strict` by default.  After that accessing any attribute raises immediately.  Typically you would just use `when`.  Actually, I don't know if I personally ever tried/used  `when2` with `mock`s.  But you could try `mock(A, strict=False)` of course.  

Although mocks are dumb, some dunder methods are defined for convenience, `__repr__` amongst them.

**Comment by kaste** [comment]
Maybe a special form `when2("a.f")` could be implemented.

**Comment by kaste** [comment]
Just checked!  `when2` does *not* work here, basically because `mock`s are too dynamic.  `when2` was probably designed with patching objects in mind.  Internally `when2` does access e.g. `a.f` *twice* and mocks give different return values on *each* usage.  This could likely be fixed as the second call is ironically just the sanity check, a final assertion, that fails.

**Comment by kaste** [comment]
The form `when2(m.foo)` now works (for dumb mocks).  For strict mocks, it doesn't as the attribute access of unconfigured attributes already raises by design.  

The general string for, e.g. `when2("os.path.exists"` is already implemented.  However, the string form always expects that it denotes an importable thing.  E.g. `from os.path import exists`.   In contrast, `when2("m.foo")` would point to a local variable, and that is -- although doable -- confusing.  Hence it is not implemented as for now.
